# SCUBA - Secure Controlled Upload BAckend
spring.application.name=SCUBA

# Server
server.port=8080

# Upload limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Storage backend
scuba.storage.type=filesystem
scuba.storage.path=generated/repository

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
